import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="https://images.prismic.io/brendaensjoerd/Z6zldpbqstJ9-itJ_favicon.ico" />
      </head>
      <body className="bg-white text-neutral-700 tracking-wide">
        {/* <div className="overflow-x-hidden"> */}
        <script async defer src="https://static.cdn.prismic.io/prismic.js?new=true&repo=brendaensjoerd"></script>
        <Analytics />
        <SpeedInsights />
        {children}
        {/* </div> */}
      </body>
    </html>
  );
}
