// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accomodation: dynamic(() => import("./Accomodation")),
  bio: dynamic(() => import("./Bio")),
  hero: dynamic(() => import("./Hero")),
  party: dynamic(() => import("./Party")),
  place: dynamic(() => import("./Place")),
  registry: dynamic(() => import("./Registry")),
  rsvp: dynamic(() => import("./Rsvp")),
  travel: dynamic(() => import("./Travel")),
};
